%global __brp_check_rpaths %{nil}
%global packname  hidetify
%global packver   0.0.1
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.0.1
Release:          1%{?dist}%{?buildtag}
Summary:          Identify Influential Observations in High Dimension

License:          GPL-3
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.6
Requires:         R-core >= 3.6
BuildRequires:    R-CRAN-Rcpp >= 1.0.7
BuildRequires:    R-CRAN-MASS 
BuildRequires:    R-stats 
BuildRequires:    R-CRAN-RcppArmadillo 
Requires:         R-CRAN-Rcpp >= 1.0.7
Requires:         R-CRAN-MASS 
Requires:         R-stats 

%description
Efficient tool for identifying influential observations in high
dimensional linear regression. The tool implements two detection
techniques single detection (Barry et al. (2020)
<doi:10.1080/03610926.2020.1841793>) and multiple detection (Barry et al.
(2021) <arXiv:2105.12286>).  The single detection is an adaptation of
Cook's measure for high dimensional data. The method relies on the concept
of expectile to construct an influence measure based on asymmetric
correlations. The multiple detection technique applies a group deletion
procedure to build the algorithm on three main steps. The first stage
applies an ultra conservative score to mitigate the swamping effect, the
second stage uses the clean sample generated in the previous stage and
applies an aggressive score to attenuate the masking phenomenon. Finally,
the last step is concerned with the validation of the influential set
generated by the two previous steps. The main functions take a response
variable and a design matrix as input and output a set of potential
influential observations.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
