%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  iop
%global packver   0.1.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.1.0
Release:          1%{?dist}%{?buildtag}
Summary:          Inflated Ordered Probit and Logit Models

License:          GPL-3
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 4.0
Requires:         R-core >= 4.0
BuildRequires:    R-CRAN-Rcpp 
BuildRequires:    R-stats 
BuildRequires:    R-graphics 
BuildRequires:    R-methods 
BuildRequires:    R-CRAN-numDeriv 
BuildRequires:    R-CRAN-MASS 
Requires:         R-CRAN-Rcpp 
Requires:         R-stats 
Requires:         R-graphics 
Requires:         R-methods 
Requires:         R-CRAN-numDeriv 
Requires:         R-CRAN-MASS 

%description
Estimation, inference, and quantities of interest for ordered probit and
ordered logit models whose outcome contains an inflated category: a single
ordered category (bottom, middle, top, or any other) that mixes
observations generated by the ordered process with observations generated
by a distinct split-population process. Fits the zero-inflated ordered
probit of Harris and Zhao (2007) <doi:10.1016/j.jeconom.2007.01.002> and
its middle- and top-inflated extensions (Bagozzi and Mukherjee 2012
<doi:10.1093/pan/mps020>; Bagozzi, Hill, Moore and Mukherjee 2015
<doi:10.1177/0022002713520530>; Bagozzi, Joo and Mukherjee 2024
<doi:10.1093/fpa/orae006>), generalized to an arbitrary inflated category
and to the logit link, with optional correlated errors for the probit
form, plus the standard ordered probit and logit and their partial
proportional-odds (non-parallel) variants on the same footing. Provides
analytic, robust, and cluster-robust standard errors, survey weights and
offsets, model comparison (Vuong, likelihood-ratio, information criteria),
regime-specific predicted probabilities and first differences, simulation
for residual diagnostics, and tidy/table-package integration. The
likelihood, its gradient, and the bivariate-normal probabilities are
implemented in C++.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
