%global packname  rsurfer
%global packver   0.2
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.2
Release:          1%{?dist}%{?buildtag}
Summary:          Manipulating 'Freesurfer' Generated Data

License:          MIT + file LICENSE
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.3.3
Requires:         R-core >= 3.3.3
BuildArch:        noarch
BuildRequires:    R-CRAN-gdata >= 2.17.0
BuildRequires:    R-CRAN-stringr >= 1.1.0
Requires:         R-CRAN-gdata >= 2.17.0
Requires:         R-CRAN-stringr >= 1.1.0

%description
The software suite, 'Freesurfer', is a open-source software suite
involving the segmentation of brain MRIs (see <http://freesurfer.net/> for
more information). This package provides functionality to import the data
generated by 'Freesurfer'; functions to easily manipulate the data; and
provides brain specific normalisation commonly used when studying
structural brain MRIs. This package has been designed using an
installation of and data generated from 'Freesurfer' version 5.3.

%prep
%setup -q -c -n %{packname}

find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
