%global __brp_check_rpaths %{nil}
%global packname  PWFSLSmoke
%global packver   1.2.117
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.2.117
Release:          1%{?dist}%{?buildtag}
Summary:          Utilities for Working with Air Quality Monitoring Data

License:          GPL-3
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.5.0
Requires:         R-core >= 3.5.0
BuildArch:        noarch
BuildRequires:    R-CRAN-dygraphs >= 1.1.1.4
BuildRequires:    R-CRAN-leaflet >= 1.0.0
BuildRequires:    R-CRAN-dplyr >= 0.8.3
BuildRequires:    R-CRAN-MazamaSpatialUtils >= 0.6.3
BuildRequires:    R-CRAN-MazamaCoreUtils >= 0.4.3
BuildRequires:    R-CRAN-maps 
BuildRequires:    R-CRAN-curl 
BuildRequires:    R-CRAN-cluster 
BuildRequires:    R-CRAN-geosphere 
BuildRequires:    R-CRAN-ggmap 
BuildRequires:    R-CRAN-glue 
BuildRequires:    R-CRAN-httr 
BuildRequires:    R-CRAN-jsonlite 
BuildRequires:    R-CRAN-lubridate 
BuildRequires:    R-CRAN-magrittr 
BuildRequires:    R-CRAN-mapproj 
BuildRequires:    R-CRAN-maptools 
BuildRequires:    R-methods 
BuildRequires:    R-CRAN-openair 
BuildRequires:    R-CRAN-png 
BuildRequires:    R-CRAN-purrr 
BuildRequires:    R-CRAN-raster 
BuildRequires:    R-CRAN-RColorBrewer 
BuildRequires:    R-CRAN-rgdal 
BuildRequires:    R-CRAN-RgoogleMaps 
BuildRequires:    R-CRAN-readr 
BuildRequires:    R-CRAN-reshape2 
BuildRequires:    R-CRAN-rlang 
BuildRequires:    R-CRAN-sf 
BuildRequires:    R-CRAN-slippymath 
BuildRequires:    R-CRAN-sp 
BuildRequires:    R-CRAN-stringr 
BuildRequires:    R-CRAN-tibble 
BuildRequires:    R-CRAN-tidyr 
BuildRequires:    R-CRAN-xts 
Requires:         R-CRAN-dygraphs >= 1.1.1.4
Requires:         R-CRAN-leaflet >= 1.0.0
Requires:         R-CRAN-dplyr >= 0.8.3
Requires:         R-CRAN-MazamaSpatialUtils >= 0.6.3
Requires:         R-CRAN-MazamaCoreUtils >= 0.4.3
Requires:         R-CRAN-maps 
Requires:         R-CRAN-curl 
Requires:         R-CRAN-cluster 
Requires:         R-CRAN-geosphere 
Requires:         R-CRAN-ggmap 
Requires:         R-CRAN-glue 
Requires:         R-CRAN-httr 
Requires:         R-CRAN-jsonlite 
Requires:         R-CRAN-lubridate 
Requires:         R-CRAN-magrittr 
Requires:         R-CRAN-mapproj 
Requires:         R-CRAN-maptools 
Requires:         R-methods 
Requires:         R-CRAN-openair 
Requires:         R-CRAN-png 
Requires:         R-CRAN-purrr 
Requires:         R-CRAN-raster 
Requires:         R-CRAN-RColorBrewer 
Requires:         R-CRAN-rgdal 
Requires:         R-CRAN-RgoogleMaps 
Requires:         R-CRAN-readr 
Requires:         R-CRAN-reshape2 
Requires:         R-CRAN-rlang 
Requires:         R-CRAN-sf 
Requires:         R-CRAN-slippymath 
Requires:         R-CRAN-sp 
Requires:         R-CRAN-stringr 
Requires:         R-CRAN-tibble 
Requires:         R-CRAN-tidyr 
Requires:         R-CRAN-xts 

%description
Utilities for working with air quality monitoring data with a focus on
small particulates (PM2.5) generated by wildfire smoke. Functions are
provided for downloading available data from the United States 'EPA'
<https://www.epa.gov/outdoor-air-quality-data> and it's 'AirNow' air
quality site <https://www.airnow.gov>. Additional sources of PM2.5 data
made accessible by the package include: 'AIRSIS' (aka "Oceaneering", not
public) and 'WRCC' <https://wrcc.dri.edu/cgi-bin/smoke.pl>. Data
compilations are hosted by the USFS 'AirFire' research team
<https://www.airfire.org>.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
