%global packname  usfertilizer
%global packver   0.1.5
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.1.5
Release:          2%{?dist}
Summary:          County-Level Estimates of Fertilizer Application in USA

License:          GPL
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 2.10
Requires:         R-core >= 2.10
BuildArch:        noarch
BuildRequires:    R-CRAN-tidyverse 
Requires:         R-CRAN-tidyverse 

%description
Compiled and cleaned the county-level estimates of fertilizer, nitrogen
and phosphorus, from 1945 to 2012 in United States of America (USA).  The
commercial fertilizer data were originally generated by USGS based on the
sales data of commercial fertilizer. The manure data were estimated based
on county-level population data of livestock, poultry, and other animals.
See the user manual for detailed data sources and cleaning methods.
'usfertilizer' utilized the tidyverse to clean the original data and
provide user-friendly dataframe. Please note that USGS does not endorse
this package. Also data from 1986 is not available for now.

%prep
%setup -q -c -n %{packname}


%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}

test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/data
%{rlibdir}/%{packname}/DESCRIPTION
%{rlibdir}/%{packname}/NAMESPACE
%doc %{rlibdir}/%{packname}/NEWS.md
%{rlibdir}/%{packname}/R
%doc %{rlibdir}/%{packname}/doc
%{rlibdir}/%{packname}/INDEX
