%global __brp_check_rpaths %{nil}
%global packname  ECharts2Shiny
%global packver   0.2.13
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.2.13
Release:          3%{?dist}%{?buildtag}
Summary:          Embedding Interactive Charts Generated with ECharts Library intoShiny Applications

License:          GPL-2
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch
BuildRequires:    R-CRAN-shiny 
BuildRequires:    R-CRAN-jsonlite 
Requires:         R-CRAN-shiny 
Requires:         R-CRAN-jsonlite 

%description
Embed interactive charts to their Shiny applications. These charts will be
generated by ECharts library developed by Baidu
(<http://echarts.baidu.com/>). Current version supports line chart, bar
chart, pie chart, scatter plot, gauge, word cloud, radar chart, tree map,
and heat map.

%prep
%setup -q -c -n %{packname}


%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/DESCRIPTION
%{rlibdir}/%{packname}/NAMESPACE
%doc %{rlibdir}/%{packname}/NEWS
%{rlibdir}/%{packname}/R
%doc %{rlibdir}/%{packname}/caravan.js
%doc %{rlibdir}/%{packname}/dark-digerati.js
%doc %{rlibdir}/%{packname}/doc
%doc %{rlibdir}/%{packname}/echarts.js
%doc %{rlibdir}/%{packname}/infographic.js
%doc %{rlibdir}/%{packname}/jazz.js
%doc %{rlibdir}/%{packname}/london.js
%doc %{rlibdir}/%{packname}/macarons.js
%doc %{rlibdir}/%{packname}/roma.js
%doc %{rlibdir}/%{packname}/shine.js
%doc %{rlibdir}/%{packname}/vintage.js
%{rlibdir}/%{packname}/INDEX
