%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  MetaEntropy
%global packver   1.2
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.2
Release:          1%{?dist}%{?buildtag}
Summary:          Functional Shannon Entropy for Virome Mutational Analysis

License:          MIT + file LICENSE
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 4.1.0
Requires:         R-core >= 4.1.0
BuildArch:        noarch
BuildRequires:    R-CRAN-ggplot2 
BuildRequires:    R-CRAN-patchwork 
BuildRequires:    R-CRAN-beeswarm 
BuildRequires:    R-CRAN-knitr 
Requires:         R-CRAN-ggplot2 
Requires:         R-CRAN-patchwork 
Requires:         R-CRAN-beeswarm 
Requires:         R-CRAN-knitr 

%description
Estimates Shannon entropy, per gene and per genomic position, associated
with non-synonymous mutation frequencies in viral populations, such as
wastewater samples or quasispecies. By categorizing amino acids based on
their physicochemical properties, the package determines whether a
mutation is functionally disruptive or neutral. Provides normalized values
(0-1 scale) to facilitate the direct comparison of different genomic
positions or total functional entropy across multiple metagenomes.
Designed to analyze mutational data using tabular 'Single Nucleotide
Variant' (SNV) frequency tables generated by variant callers (e.g., 'iVar'
or 'LoFreq'), operating independently of consensus sequence estimation and
multiple sequence alignment.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
