%global packname  ecolMod
%global packver   1.2.6
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.2.6
Release:          3%{?dist}%{?buildtag}
Summary:          "A practical guide to ecological modelling - using R as asimulation platform"

License:          GPL (>= 2)
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 2.01
Requires:         R-core >= 2.01
BuildRequires:    R-CRAN-rootSolve 
BuildRequires:    R-CRAN-shape 
BuildRequires:    R-CRAN-diagram 
BuildRequires:    R-CRAN-deSolve 
Requires:         R-CRAN-rootSolve 
Requires:         R-CRAN-shape 
Requires:         R-CRAN-diagram 
Requires:         R-CRAN-deSolve 

%description
Figures, data sets and examples from the book "A practical guide to
ecological modelling - using R as a simulation platform" by Karline
Soetaert and Peter MJ Herman (2009). Springer. All figures from chapter x
can be generated by "demo(chapx)", where x = 1 to 11. The R-scripts of the
model examples discussed in the book are in subdirectory "examples",
ordered per chapter. Solutions to model projects are in the same
subdirectories.

%prep
%setup -q -c -n %{packname}


%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}

test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/data
%doc %{rlibdir}/%{packname}/demo
%{rlibdir}/%{packname}/DESCRIPTION
%{rlibdir}/%{packname}/NAMESPACE
%{rlibdir}/%{packname}/R
%doc %{rlibdir}/%{packname}/doc
%{rlibdir}/%{packname}/INDEX
%{rlibdir}/%{packname}/libs
