%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  FieldSimR
%global packver   1.3.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.3.0
Release:          1%{?dist}%{?buildtag}
Summary:          Simulation of Plot Errors and Phenotypes in Plant Breeding Field Trials

License:          GPL (>= 3)
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.5.0
Requires:         R-core >= 3.5.0
BuildArch:        noarch
BuildRequires:    R-CRAN-ggplot2 
BuildRequires:    R-CRAN-interp 
BuildRequires:    R-CRAN-lattice 
BuildRequires:    R-CRAN-mbend 
BuildRequires:    R-CRAN-cluster 
Requires:         R-CRAN-ggplot2 
Requires:         R-CRAN-interp 
Requires:         R-CRAN-lattice 
Requires:         R-CRAN-mbend 
Requires:         R-CRAN-cluster 

%description
Simulates plot data in multi-environment field trials with one or more
traits. Its core function generates plot errors that capture spatial
trend, random error (noise), and extraneous variation, which are combined
at a user-defined ratio. Phenotypes can be generated by combining the plot
errors with simulated genetic values that capture genotype-by-environment
(GxE) interaction using wrapper functions for the R package `AlphaSimR`.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
