%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  antaresViz
%global packver   0.18.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.18.0
Release:          1%{?dist}%{?buildtag}
Summary:          Antares Visualizations

License:          GPL (>= 2) | file LICENSE
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch
BuildRequires:    R-CRAN-plotly >= 4.5.6
BuildRequires:    R-CRAN-antaresRead >= 2.2.9
BuildRequires:    R-CRAN-sp >= 2.0.0
BuildRequires:    R-CRAN-dygraphs >= 1.1.1.6
BuildRequires:    R-CRAN-leaflet >= 1.1.0
BuildRequires:    R-CRAN-htmlwidgets >= 0.7.0
BuildRequires:    R-CRAN-leaflet.minicharts >= 0.5.3
BuildRequires:    R-CRAN-spMaps >= 0.5.0
BuildRequires:    R-CRAN-antaresProcessing >= 0.13.0
BuildRequires:    R-CRAN-shiny >= 0.13.0
BuildRequires:    R-CRAN-manipulateWidget >= 0.10.0
BuildRequires:    R-CRAN-htmltools 
BuildRequires:    R-CRAN-sf 
BuildRequires:    R-CRAN-webshot 
BuildRequires:    R-CRAN-data.table 
BuildRequires:    R-methods 
BuildRequires:    R-CRAN-lubridate 
BuildRequires:    R-CRAN-geojsonio 
BuildRequires:    R-graphics 
BuildRequires:    R-stats 
BuildRequires:    R-CRAN-assertthat 
BuildRequires:    R-CRAN-rAmCharts 
BuildRequires:    R-utils 
Requires:         R-CRAN-plotly >= 4.5.6
Requires:         R-CRAN-antaresRead >= 2.2.9
Requires:         R-CRAN-sp >= 2.0.0
Requires:         R-CRAN-dygraphs >= 1.1.1.6
Requires:         R-CRAN-leaflet >= 1.1.0
Requires:         R-CRAN-htmlwidgets >= 0.7.0
Requires:         R-CRAN-leaflet.minicharts >= 0.5.3
Requires:         R-CRAN-spMaps >= 0.5.0
Requires:         R-CRAN-antaresProcessing >= 0.13.0
Requires:         R-CRAN-shiny >= 0.13.0
Requires:         R-CRAN-manipulateWidget >= 0.10.0
Requires:         R-CRAN-htmltools 
Requires:         R-CRAN-sf 
Requires:         R-CRAN-webshot 
Requires:         R-CRAN-data.table 
Requires:         R-methods 
Requires:         R-CRAN-lubridate 
Requires:         R-CRAN-geojsonio 
Requires:         R-graphics 
Requires:         R-stats 
Requires:         R-CRAN-assertthat 
Requires:         R-CRAN-rAmCharts 
Requires:         R-utils 

%description
Visualize results generated by Antares, a powerful open source software
developed by RTE to simulate and study electric power systems (more
information about 'Antares' here:
<https://github.com/AntaresSimulatorTeam/Antares_Simulator>). This package
provides functions that create interactive charts to help 'Antares' users
visually explore the results of their simulations.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
