%global packname  conquestr
%global packver   0.3.7
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.3.7
Release:          1%{?dist}
Summary:          An R Front End for 'ACER ConQuest'

License:          GPL-3
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch

%description
Extends 'ACER ConQuest' by allowing R users to call 'ACER ConQuest' from
within R. The user can also access 'ACER ConQuest' data objects by reading
'ACER ConQuest' System Files (generated by the 'ACER ConQuest' command
'put'). This is of particular use to those who are parsing text file
output (e.g., 'show' files) as this is not consistent across releases of
'ACER ConQuest'. Requires 'ACER ConQuest' version 4.29.3 or later. A
demonstration version can be downloaded from
<https://shop.acer.edu.au/acer-conquest-4>.

%prep
%setup -q -c -n %{packname}


%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/DESCRIPTION
%{rlibdir}/%{packname}/NAMESPACE
%{rlibdir}/%{packname}/R
%doc %{rlibdir}/%{packname}/doc
%{rlibdir}/%{packname}/extdata
%{rlibdir}/%{packname}/INDEX
