%global packname  statebins
%global packver   1.4.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.4.0
Release:          2%{?dist}%{?buildtag}
Summary:          Create United States Uniform Cartogram Heatmaps

License:          MIT + file LICENSE
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.5.0
Requires:         R-core >= 3.5.0
BuildArch:        noarch
BuildRequires:    R-CRAN-ggplot2 >= 2.2.1
BuildRequires:    R-CRAN-scales >= 0.5.0
BuildRequires:    R-grid 
Requires:         R-CRAN-ggplot2 >= 2.2.1
Requires:         R-CRAN-scales >= 0.5.0
Requires:         R-grid 

%description
The 'cartogram' heatmaps generated by the included methods are an
alternative to choropleth maps for the United States and are based on work
by the Washington Post graphics department in their report on "The states
most threatened by trade"
(<http://www.washingtonpost.com/wp-srv/special/business/states-most-threatened-by-trade/>).
"State bins" preserve as much of the geographic placement of the states as
possible but have the look and feel of a traditional heatmap. Functions
are provided that allow for use of a binned, discrete scale, a continuous
scale or manually specified colors depending on what is needed for the
underlying data.

%prep
%setup -q -c -n %{packname}

find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
