%global packname  glmglrt
%global packver   0.1.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.1.0
Release:          1%{?dist}
Summary:          GLRT P-Values in Generalized Linear Models

License:          GPL-2
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch
BuildRequires:    R-CRAN-parameters >= 0.1.0
BuildRequires:    R-base 
BuildRequires:    R-stats 
BuildRequires:    R-MASS 
Requires:         R-CRAN-parameters >= 0.1.0
Requires:         R-base 
Requires:         R-stats 
Requires:         R-MASS 

%description
Provides functions to compute Generalized Likelihood Ratio Tests (GLRT)
and Rao's score tests of simple and complex contrasts of Generalized
Linear Models (GLMs). It provides the same interface as summary.glm(),
adding GLRT P-values, less biased than Wald's P-values and consistent with
profile-likelihood confidence interval generated by confint().

%prep
%setup -q -c -n %{packname}

find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}

test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/DESCRIPTION
%{rlibdir}/%{packname}/NAMESPACE
%{rlibdir}/%{packname}/R
%{rlibdir}/%{packname}/INDEX
