%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  mazealls
%global packver   0.2.1
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.2.1
Release:          1%{?dist}%{?buildtag}
Summary:          Generate Recursive Mazes

License:          LGPL-3
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.0.2
Requires:         R-core >= 3.0.2
BuildArch:        noarch
BuildRequires:    R-CRAN-TurtleGraphics 
Requires:         R-CRAN-TurtleGraphics 

%description
Supports the generation of parallelogram, equilateral triangle, regular
hexagon, isosceles trapezoid, Koch snowflake, 'hexaflake', Sierpinski
triangle, Sierpinski carpet and Sierpinski trapezoid mazes via
'TurtleGraphics'. Mazes are generated by the recursive method: the domain
is divided into sub-domains in which mazes are generated, then dividing
lines with holes are drawn between them, see J. Buck, Recursive Division,
<http://weblog.jamisbuck.org/2011/1/12/maze-generation-recursive-division-algorithm>.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
