%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  FieldSimR
%global packver   1.2.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.2.0
Release:          1%{?dist}%{?buildtag}
Summary:          Simulation of Plot Errors and Phenotypes in Plant Breeding Field Trials

License:          GPL (>= 3)
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 2.10
Requires:         R-core >= 2.10
BuildArch:        noarch
BuildRequires:    R-CRAN-ggplot2 
BuildRequires:    R-CRAN-interp 
BuildRequires:    R-CRAN-lattice 
BuildRequires:    R-CRAN-matrixcalc 
BuildRequires:    R-CRAN-mbend 
Requires:         R-CRAN-ggplot2 
Requires:         R-CRAN-interp 
Requires:         R-CRAN-lattice 
Requires:         R-CRAN-matrixcalc 
Requires:         R-CRAN-mbend 

%description
Simulates plot data in field trials for multiple traits across multiple
environments. Its core function generates plot errors comprising 1) a
spatially correlated error term, 2) a random error term, and 3) an
extraneous error term. Spatially correlated errors are simulated using
either bivariate interpolation or a two-dimensional autoregressive process
of order one (AR1:AR1). The three error terms are combined at a
user-defined ratio. Plot phenotypes can be generated by combining the
simulated errors with genetic values (e.g. true, simulated or predicted).
'FieldSimR' provides wrapper functions to simulate genetic values for
multiple traits across multiple environments using the 'R' package
'AlphaSimR'.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
