%global packname  antaresProcessing
%global packver   0.18.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.18.0
Release:          2%{?dist}
Summary:          'Antares' Results Processing

License:          GPL (>= 2) | file LICENSE
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch
BuildRequires:    R-CRAN-antaresRead >= 1.1.5
BuildRequires:    R-CRAN-data.table 
BuildRequires:    R-methods 
BuildRequires:    R-stats 
Requires:         R-CRAN-antaresRead >= 1.1.5
Requires:         R-CRAN-data.table 
Requires:         R-methods 
Requires:         R-stats 

%description
Process results generated by 'Antares', a powerful open source software
developed by RTE (Réseau de Transport d’Électricité) to simulate and study
electric power systems (more information about 'Antares' here:
<https://github.com/AntaresSimulatorTeam/Antares_Simulator>). This package
provides functions to create new columns like net load, load factors,
upward and downward margins or to compute aggregated statistics like
economic surpluses of consumers, producers and sectors.

%prep
%setup -q -c -n %{packname}

find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}

test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/DESCRIPTION
%license %{rlibdir}/%{packname}/LICENSE
%{rlibdir}/%{packname}/NAMESPACE
%doc %{rlibdir}/%{packname}/NEWS
%{rlibdir}/%{packname}/R
%doc %{rlibdir}/%{packname}/doc
%{rlibdir}/%{packname}/testdata
%{rlibdir}/%{packname}/INDEX
