%global packname  GaDiFPT
%global packver   1.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          1.0
Release:          3%{?dist}%{?buildtag}
Summary:          First Passage Time Simulation for Gaussian Diffusion Processes

License:          GPL-2
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch

%description
In this package we consider Gaussian Diffusion processes and smooth
thresholds. After evaluating the mean of the process to check the
subthreshold regimen hypothesis, the FPT density function is reconstructed
via the numerical quadrature of the integral equation in (Buonocore 1987);
first passage times are also generated by the method in (Buonocore 2014)
and results are compared. The timestep of the simulations can iteratively
be refined. User should provide the functional form for the drift and the
infinitesimal variance in the script 'userfunc.R' and for the threshold in
the script 'userthresh.R'. All the parameters required by the
implementation are to be set in the script 'userparam.R'. Example scripts
for common drifts and thresholds are given.

%prep
%setup -q -c -n %{packname}


%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%doc %{rlibdir}/%{packname}/demo
%{rlibdir}/%{packname}/DESCRIPTION
%{rlibdir}/%{packname}/NAMESPACE
%{rlibdir}/%{packname}/R
%{rlibdir}/%{packname}/INDEX
