%global __brp_check_rpaths %{nil}
%global __requires_exclude ^libmpi
%global packname  harf
%global packver   0.1.0
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.1.0
Release:          1%{?dist}%{?buildtag}
Summary:          Adversarial Random Forests for Omics Synthesis

License:          GPL-3
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel >= 3.6.0
Requires:         R-core >= 3.6.0
BuildArch:        noarch
BuildRequires:    R-CRAN-arf 
BuildRequires:    R-CRAN-data.table 
BuildRequires:    R-stats 
BuildRequires:    R-CRAN-ClusterR 
BuildRequires:    R-CRAN-matrixStats 
BuildRequires:    R-CRAN-pracma 
BuildRequires:    R-CRAN-pls 
BuildRequires:    R-CRAN-fastPLS 
BuildRequires:    R-CRAN-RGCCA 
BuildRequires:    R-CRAN-ranger 
BuildRequires:    R-CRAN-rsvd 
BuildRequires:    R-CRAN-foreach 
Requires:         R-CRAN-arf 
Requires:         R-CRAN-data.table 
Requires:         R-stats 
Requires:         R-CRAN-ClusterR 
Requires:         R-CRAN-matrixStats 
Requires:         R-CRAN-pracma 
Requires:         R-CRAN-pls 
Requires:         R-CRAN-fastPLS 
Requires:         R-CRAN-RGCCA 
Requires:         R-CRAN-ranger 
Requires:         R-CRAN-rsvd 
Requires:         R-CRAN-foreach 

%description
We extend Adversarial Random Forests to a high-dimensional framework. The
method partitions the feature space into regions where the assumption of
feature independence within tree leaves is more likely to hold.
Region-specific adversarial random forest models are trained to capture
local dependence structures, while an additional adversarial random forest
is fitted to a meta-space representation to model dependencies between
regions. New observations are generated by first sampling from the
meta-space model and then conditionally sampling from each region-specific
model. The proposed methodology is described in Fouodo et al. (2026)
<doi:10.64898/2026.09.09.750490>.

%prep
%setup -q -c -n %{packname}

# fix end of executable files
find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;
# prevent binary stripping
[ -d %{packname}/src ] && find %{packname}/src -type f -exec \
  sed -i 's@/usr/bin/strip@/usr/bin/true@g' {} \; || true
[ -d %{packname}/src ] && find %{packname}/src/Make* -type f -exec \
  sed -i 's@-g0@@g' {} \; || true
# don't allow local prefix in executable scripts
find -type f -executable -exec sed -Ei 's@#!( )*/usr/local/bin@#!/usr/bin@g' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css
# remove buildroot from installed files
find %{buildroot}%{rlibdir} -type f -exec sed -i "s@%{buildroot}@@g" {} \;

%files
%{rlibdir}/%{packname}
