%global packname  antaresViz
%global packver   0.15.2
%global rlibdir   /usr/local/lib/R/library

Name:             R-CRAN-%{packname}
Version:          0.15.2
Release:          3%{?dist}
Summary:          Antares Visualizations

License:          GPL (>= 2) | file LICENSE
URL:              https://cran.r-project.org/package=%{packname}
Source0:          %{url}&version=%{packver}#/%{packname}_%{packver}.tar.gz


BuildRequires:    R-devel
Requires:         R-core
BuildArch:        noarch
BuildRequires:    R-CRAN-plotly >= 4.5.6
BuildRequires:    R-CRAN-antaresRead >= 2.0.0
BuildRequires:    R-CRAN-dygraphs >= 1.1.1.6
BuildRequires:    R-CRAN-leaflet >= 1.1.0
BuildRequires:    R-CRAN-htmlwidgets >= 0.7.0
BuildRequires:    R-CRAN-leaflet.minicharts >= 0.5.3
BuildRequires:    R-CRAN-spMaps >= 0.2
BuildRequires:    R-CRAN-antaresProcessing >= 0.13.0
BuildRequires:    R-CRAN-shiny >= 0.13.0
BuildRequires:    R-CRAN-manipulateWidget >= 0.10.0
BuildRequires:    R-CRAN-htmltools 
BuildRequires:    R-CRAN-sp 
BuildRequires:    R-CRAN-rgeos 
BuildRequires:    R-CRAN-raster 
BuildRequires:    R-CRAN-webshot 
BuildRequires:    R-CRAN-data.table 
BuildRequires:    R-methods 
BuildRequires:    R-CRAN-lubridate 
BuildRequires:    R-CRAN-geojsonio 
BuildRequires:    R-graphics 
BuildRequires:    R-stats 
BuildRequires:    R-CRAN-assertthat 
BuildRequires:    R-CRAN-rAmCharts 
BuildRequires:    R-utils 
Requires:         R-CRAN-plotly >= 4.5.6
Requires:         R-CRAN-antaresRead >= 2.0.0
Requires:         R-CRAN-dygraphs >= 1.1.1.6
Requires:         R-CRAN-leaflet >= 1.1.0
Requires:         R-CRAN-htmlwidgets >= 0.7.0
Requires:         R-CRAN-leaflet.minicharts >= 0.5.3
Requires:         R-CRAN-spMaps >= 0.2
Requires:         R-CRAN-antaresProcessing >= 0.13.0
Requires:         R-CRAN-shiny >= 0.13.0
Requires:         R-CRAN-manipulateWidget >= 0.10.0
Requires:         R-CRAN-htmltools 
Requires:         R-CRAN-sp 
Requires:         R-CRAN-rgeos 
Requires:         R-CRAN-raster 
Requires:         R-CRAN-webshot 
Requires:         R-CRAN-data.table 
Requires:         R-methods 
Requires:         R-CRAN-lubridate 
Requires:         R-CRAN-geojsonio 
Requires:         R-graphics 
Requires:         R-stats 
Requires:         R-CRAN-assertthat 
Requires:         R-CRAN-rAmCharts 
Requires:         R-utils 

%description
Visualize results generated by Antares, a powerful open source software
developed by RTE to simulate and study electric power systems (more
information about Antares here:
<https://github.com/AntaresSimulatorTeam/Antares_Simulator>). This package
provides functions that create interactive charts to help Antares users
visually explore the results of their simulations.

%prep
%setup -q -c -n %{packname}

find -type f -executable -exec grep -Iq . {} \; -exec sed -i -e '$a\' {} \;

%build

%install

mkdir -p %{buildroot}%{rlibdir}
%{_bindir}/R CMD INSTALL -l %{buildroot}%{rlibdir} %{packname}

test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)
rm -f %{buildroot}%{rlibdir}/R.css

%files
%dir %{rlibdir}/%{packname}
%doc %{rlibdir}/%{packname}/html
%{rlibdir}/%{packname}/Meta
%{rlibdir}/%{packname}/help
%{rlibdir}/%{packname}/DESCRIPTION
%license %{rlibdir}/%{packname}/LICENSE
%{rlibdir}/%{packname}/NAMESPACE
%doc %{rlibdir}/%{packname}/NEWS.md
%{rlibdir}/%{packname}/R
%doc %{rlibdir}/%{packname}/AntaresViz.xlsx
%doc %{rlibdir}/%{packname}/application
%doc %{rlibdir}/%{packname}/color.csv
%doc %{rlibdir}/%{packname}/doc
%doc %{rlibdir}/%{packname}/GraphicalCharter.csv
%{rlibdir}/%{packname}/htmlwidgets
%doc %{rlibdir}/%{packname}/js_dates_locales.csv
%doc %{rlibdir}/%{packname}/language_columns.csv
%doc %{rlibdir}/%{packname}/language_labels.csv
%doc %{rlibdir}/%{packname}/leafletPlugins
%doc %{rlibdir}/%{packname}/mapLayout
%doc %{rlibdir}/%{packname}/moduleDev
%doc %{rlibdir}/%{packname}/test_scripts
%{rlibdir}/%{packname}/INDEX
