name: Create and push docker images

on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.release }}
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        config:
          release: [34, 35, rawhide]

    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}

    steps:
    - name: Downcase IMAGE
      run:  echo "IMAGE=${IMAGE,,}" >> ${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.config.release }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.config.release }}-

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: $REGISTRY
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker
        push: true
        build-args: VERSION=${{ matrix.config.release }}
        tags: $REGISTRY/$IMAGE:${{ matrix.config.release }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
