name: Docker images

on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: ${{ matrix.release }}
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        release: [35, 36, rawhide]

    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }}

    steps:
    - name: Downcase IMAGE
      run:  echo "IMAGE=${IMAGE,,}" >> ${GITHUB_ENV}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.release }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.release }}-

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: docker
        pull: true
        push: true
        build-args: VERSION=${{ matrix.release }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ matrix.release }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
