name: Docker images

on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: ${{ matrix.tag }}
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        tag: [41, 42, rawhide]

    env:
      REGISTRY: ghcr.io/cran4linux

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.tag }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.tag }}-

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push r-fedora
      uses: docker/build-push-action@v6
      with:
        context: docker
        target: r-fedora
        pull: true
        push: true
        build-args: VERSION=${{ matrix.tag }}
        tags: ${{ env.REGISTRY }}/r-fedora:${{ matrix.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Build and push r-copr
      uses: docker/build-push-action@v6
      with:
        context: docker
        target: r-copr
        pull: true
        push: true
        build-args: VERSION=${{ matrix.tag }}
        tags: ${{ env.REGISTRY }}/r-copr:${{ matrix.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
