name: Daily sync

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    container: ghcr.io/cran4linux/r-fedora:38
    steps:
    - name: Configuration
      run: |
        sudo dnf -y install git copr-cli
        git config --global user.name "Github Action"
        git config --global user.email "enchufa2@users.noreply.github.com"
        mkdir -p $HOME/.config && echo "$TOKEN" > $HOME/.config/copr
      env:
        TOKEN: ${{ secrets.COPR_TOKEN }}
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Sync with CRAN
      run: |
        Rscript copr-sync.r || touch failure
        git add specs
        git diff-index --quiet HEAD || git commit -m "sync"
        git push
        ! test -f failure
